### ISSUE TITLE
Процесс лаунчера закрылся слишком быстро

### ISSUE THREAD

**Issue by OppositeOfDisorder** [GravitLauncher/LauncherPrestarter#12]
![image](https://github.com/GravitLauncher/LauncherPrestarter/assets/33712764/e6fc87d6-39f2-4525-9327-5a0223b8bd3c)
Поменял только переменную Project и форму. LauncherURL = null

**Comment by DearFox** [comment]
Иногда еще такая ошибка может возникунть, когда файл лаунчера Launcher.jar качается битый.
Тогда нужно в ручную его удалить что-бы оно его перекачало.
